version: '3'
services:
    racingdb:
        build: repository/
        hostname: "racingdb"
        ports:
            - "5432"
        labels:
            NAME: "racingdb"
    restserver:
        build: api/
        environment:
            - PORT_NUM=80
        ports:
            - "80:80"
    racingservice:
        build: racingservice/
        environment:
            - DBURI=postgres://ladbrokes:hu8jmn3@articledb:5432/race_data_db?sslmode=disable
            - PORT_NUM=5200
        ports:
            - "5200"
        depends_on:
            - racingdb
